Traceback (most recent call last):
  File "/home/abdelmajid/workdir/cost-aware-bo/main.py", line 66, in <module>
    trial_logs = bo_trial(trial_number=trial, acqf=args.acqf, wandb=wandb, params=params)
  File "/home/abdelmajid/workdir/cost-aware-bo/single_trial.py", line 37, in bo_trial
    input_bounds = get_gen_bounds(h_ind, bound_list, funcs=chosen_functions)
  File "/home/abdelmajid/workdir/cost-aware-bo/functions.py", line 114, in get_gen_bounds
    bounds = torch.tensor([lo_bounds, hi_bounds], device=DEVICE, dtype=torch.double)
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.